GET http://localhost:3000/books

###
POST http://localhost:3000/books
Content-Type: application/json

{
  "titulo": "Harry Potter e o Prisioneiro de Azkaban",
  "autor": "J.K. Rowling",
  "status": "Lido",
  "avaliacao": 5,
  "usuario_id": 2
}


###
GET http://localhost:3000/books/5

###
PUT http://localhost:3000/books/5/1
Content-Type: application/json

{
  "titulo": "A Revolução dos Bichos",
  "autor": "George Orwell",
  "status": "Lido",
  
  
  "usuario_id": 4
}


###

DELETE http://localhost:3000/books/3/1