POST http://localhost:3000/users
Content-Type: application/json

{
  "nome": "henrique c melo",
  "email": "hcm@aa.com"

}

### 

GET http://localhost:3000/users

###

PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "nome": "Guilherme",
  "email": "guilherme@gui.com"
}

###
DELETE http://localhost:3000/users/3